config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("", include('core.urls', namespace="core")),
    path('rooms/', include('rooms.urls', namespace='rooms')),
    path('users/', include('users.urls', namespace='users')),
    path('lists/', include('lists.urls', namespace='lists')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
from rooms import views as rooms_views

app_name = "core"

urlpatterns = [
    path("", rooms_views.HomeView.as_view(), name="home"),
]

lists/urls.py
from django.urls import path

from lists.views import toggle_room, SeeFavsView

app_name = "lists"

urlpatterns = [
    path("toggle/<int:room_pk>", toggle_room, name="toggle-room"),
    path("favs/", SeeFavsView.as_view(), name="see-favs"),
]

rooms/urls.py
from django.urls import path

from rooms.views import RoomDetail, EditRoomView, CreateRoomView, SearchView, RoomPhotosView, delete_photo, EditPhotoView, AddPhotoView

app_name = "rooms"

urlpatterns = [
    path("create/", CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", AddPhotoView.as_view(), name="add-photos"),
    path("<int:room_pk>/photos/<int:photo_pk>/delete/", delete_photo, name="delete-photo"),
    path("<int:room_pk>/photos/<int:photo_pk>/edit/", EditPhotoView.as_view(), name="edit-photo"),
    path("search/", SearchView.as_view(), name="search"),
]

users/urls.py
from django.urls import path

from users.views import LoginView, log_out, SignUpView, complete_verification, github_login, github_callback, \
    kakao_callback, kakao_login, UserProfileView, UpdateUserProfileView, UpdateUserPasswordView, switch_hosting

app_name = "users"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("login/github/", github_login, name="github-login"),
    path("login/github/callback/", github_callback, name="github-callback"),
    path("login/kakao/", kakao_login, name="kakao-login"),
    path("login/kakao/callback/", kakao_callback, name="kakao-callback"),
    path("logout/", log_out, name="logout"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("verify/<str:key>/", complete_verification, name="complete_verification"),
    path("<int:pk>/", UserProfileView.as_view(), name="profile"),
    path("update-profile/", UpdateUserProfileView.as_view(), name="update"),
    path("update-password/", UpdateUserPasswordView.as_view(), name="update-password"),
    path("switch-hosting/", switch_hosting, name="switch-hosting"),
]

templates/partials/footer.html
<footer class="container mx-auto text-center py-10 border-t font-medium text-gray-500">
    &copy; 2021 breeze_bnb
</footer>

templates/partials/messages.html
{% if messages %}
    <ul class="absolute top-0 mx-auto left-0 right-0 flex justify-center">
        {% for message in messages %}
            <li class="message z-10 font-medium bg-gray-700 rounded-full text-white py-4 px-6 w-64 text-center {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

templates/partials/nav.html
<ul class="flex items-center text-sm font-medium h-full">
    {% if user.is_authenticated %}
    <li class="nav_link">
        <a href="{% url "users:switch-hosting" %}">
            {% if request.session.is_hosting %}
                Stop Hosting
            {% else %}
                Start Hosting
            {% endif %}
        </a>
    </li>
        {% if request.session.is_hosting %}
            <li class="nav_link"><a href="{% url "rooms:create" %}">Create Room</a></li>
        {% endif %}
        <li class="nav_link"><a href="{% url "lists:see-favs" %}">Favorite</a></li>
        <li class="nav_link"><a href="{{ user.get_absolute_url }}">Profile</a></li>
        <li class="nav_link"><a href="{% url "users:logout" %}">Log out</a></li>
    {% else %}
        <li class="nav_link"><a href="{% url "users:login" %}">Log in</a></li>
        <li class="nav_link"><a href="{% url "users:signup" %}">Sign Up</a></li>
    {% endif %}
</ul>

templates/partials/social_login.html
<div class="flex flex-col w-full">
    <a href="{% url "users:github-login" %}" class="btn border-2 border-gray-700 text-gray-700 mb-2">
        <i class="fab fa-github-alt mr-2 fa-lg"></i>
        Continue with GitHub
    </a>
    <a href="{% url "users:kakao-login" %}" class="btn border border-yellow-300 text-yellow-700 mb-2 bg-yellow-300">
        <i class="fas fa-comment mr-2 fa-lg"></i>
        Continue with KaKao
    </a>
</div>
<div class="flex items-center w-full my-5">
    <div class="h-px w-full bg-gray-400"></div>
    <span class="text-gray-600 font-medium text-sm mx-4">or</span>
    <div class="h-px w-full bg-gray-400"></div>
</div>