config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("", include('core.urls', namespace="core")),
    path('rooms/', include('rooms.urls', namespace='rooms')),
    path('users/', include('users.urls', namespace='users')),
    path('lists/', include('lists.urls', namespace='lists')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
from rooms import views as rooms_views

app_name = "core"

urlpatterns = [
    path("", rooms_views.HomeView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path

from rooms.views import RoomDetail, EditRoomView, CreateRoomView, SearchView, RoomPhotosView, delete_photo, EditPhotoView, AddPhotoView

app_name = "rooms"

urlpatterns = [
    path("create/", CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", AddPhotoView.as_view(), name="add-photos"),
    path("<int:room_pk>/photos/<int:photo_pk>/delete/", delete_photo, name="delete-photo"),
    path("<int:room_pk>/photos/<int:photo_pk>/edit/", EditPhotoView.as_view(), name="edit-photo"),
    path("search/", SearchView.as_view(), name="search"),
]

rooms/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django_countries.fields import CountryField

from cal import Calendar
from core import models as core_models


class AbstractItem(core_models.TimeStampedModel):
    """ Abstract Room Item """

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):
    """ Room Type Model Definition """

    class Meta:
        verbose_name_plural = 'Room Type'
        ordering = ['-created_at']


class Amenity(AbstractItem):
    """ Amenity Model Definition """

    class Meta:
        verbose_name_plural = 'Amenities'


class Facility(AbstractItem):
    """ Facility Model Definition """

    class Meta:
        verbose_name_plural = 'Facilities'


class HouseRule(AbstractItem):
    """ HoseRule Model Definition """

    class Meta:
        verbose_name_plural = 'House_Rules'


class Photo(core_models.TimeStampedModel):
    """ Photo Model Definition """
    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to='room_photos')
    room = models.ForeignKey('Room', related_name='photos', on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


class Room(core_models.TimeStampedModel):
    """ Room Model Definition """

    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    guests = models.IntegerField()
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    host = models.ForeignKey('users.User', related_name='rooms', on_delete=models.CASCADE)
    room_type = models.ForeignKey('RoomType', related_name='rooms', on_delete=models.SET_NULL, null=True)
    amenities = models.ManyToManyField('Amenity', related_name='rooms', blank=True)
    facilities = models.ManyToManyField('Facility', related_name='rooms', blank=True)
    house_rules = models.ManyToManyField('HouseRule', related_name='rooms', blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={'pk': self.pk})

    def total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        for review in all_reviews:
            all_ratings += review.rating_average()
        try:
            rating = round(all_ratings / len(all_reviews), 2)
        except ZeroDivisionError:
            rating = '-'
        return rating

    def first_photo(self):
        # Array unpacking
        try:
            photo, = self.photos.all()[:1]
            return photo.file.url
        except ValueError:
            return None

    def get_next_four_photos(self):
        photos = self.photos.all()[1:5]
        print(photos)
        return photos

    def get_calendars(self):
        now = timezone.now()
        this_year = now.year
        this_month = now.month
        next_month = this_month + 1
        if this_month == 12:
            this_year += 1
            next_month = 1
        this_month_cal = Calendar(this_year, this_month)
        next_month_cal = Calendar(this_year, next_month)
        return [this_month_cal, next_month_cal]

rooms/forms.py
from django import forms
from django_countries.fields import CountryField

from rooms.models import RoomType, Amenity, Facility, Photo, Room


class SearchForm(forms.Form):
    city = forms.CharField(initial="Anywhere")
    country = CountryField(default="KR").formfield()
    room_type = forms.ModelChoiceField(required=False, empty_label="Any Kind", queryset=RoomType.objects.all())
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(required=False, queryset=Amenity.objects.all(), widget=forms.CheckboxSelectMultiple)
    facilities = forms.ModelMultipleChoiceField(required=False, queryset=Facility.objects.all(), widget=forms.CheckboxSelectMultiple)


class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ("caption", "file",)

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        room = Room.objects.get(pk=pk)
        photo.room = room
        photo.save()


class CreateRoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = (
            "name",
            "description",
            "country",
            "city",
            "price",
            "address",
            "guests",
            "beds",
            "bedrooms",
            "baths",
            "check_in",
            "check_out",
            "instant_book",
            "room_type",
            "amenities",
            "facilities",
            "house_rules",
        )

    def save(self, *args, **kwargs):
        room = super().save(commit=False)
        return room

rooms/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views.generic import ListView, DetailView, UpdateView, CreateView, FormView, View

from rooms.forms import SearchForm, CreatePhotoForm, CreateRoomForm
from rooms.models import Room, RoomType, Amenity, Facility, HouseRule, Photo
from users import mixins


class HomeView(ListView):
    """ HomeView Definition """

    model = Room
    paginate_by = 20
    ordering = "created_at"
    paginate_orphans = 3
    context_object_name = "rooms"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        now = timezone.now()
        context["now"] = now
        return context


class RoomDetail(DetailView):
    """ Room Detail Definition"""

    model = Room


# # FBV
# def room_detail(request, pk):
#     try:
#         room = Room.objects.get(pk=pk)
#         return render(request, 'rooms/detail.html', {'room':room})
#     except Room.DoesNotExist:
#         raise Http404()


class EditRoomView(mixins.LoggedInOnlyView, UpdateView):
    """ Room Edit Definition"""

    model = Room
    template_name = "rooms/room_edit.html"
    success_url = reverse_lazy("core:home")
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "host",
        "room_type",
        "amenities",
        "facilities",
        "house_rules",
    )

    # 내가 host가 아닌 방은 수정 못함
    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room


class RoomPhotosView(mixins.LoggedInOnlyView, DetailView):
    model = Room
    template_name = "rooms/room_photos.html"

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room


@login_required
def delete_photo(request, room_pk, photo_pk):
    user = request.user
    try:
        room = Room.objects.get(pk=room_pk)
        if room.host.pk != user.pk:
            messages.error(request, "can't delete that photo")
        else:
            Photo.objects.filter(pk=photo_pk).delete()
            messages.success(request, "Photo Deleted!")
        return redirect(reverse("rooms:photos", kwargs={"pk": room_pk}))
    except Room.DoesNotExist:
        return redirect(reverse("core:home"))


class EditPhotoView(mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):
    model = Photo
    template_name = "rooms/photo_edit.html"
    pk_url_kwarg = "photo_pk"
    success_message = "Photo Updated!"
    fields = ("caption",)

    def get_success_url(self):
        room_pk = self.kwargs.get("room_pk")
        return reverse("rooms:photos", kwargs={"pk": room_pk})


class AddPhotoView(mixins.LoggedInOnlyView, SuccessMessageMixin, FormView):
    model = Photo
    template_name = "rooms/photo_create.html"
    fields = (
        "caption",
        "file",
    )
    form_class = CreatePhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        form.save(pk)
        messages.success(self.request, "Photo Upload")
        return redirect(reverse("rooms:photos", kwargs={"pk": pk}))


class CreateRoomView(mixins.LoggedInOnlyView, FormView):
    form_class = CreateRoomForm
    template_name = "rooms/room_create.html"

    def form_valid(self, form):
        room = form.save(self.request.user)
        room.host = self.request.user
        room.save()
        # many to many field save method
        form.save_m2m()
        messages.success(self.request, "Room Created")
        return redirect(reverse("rooms:detail", kwargs={"pk": room.pk}))


class SearchView(View):
    def get(self, request):
        country = request.GET.get("country")

        if country:

            form = SearchForm(request.GET)

            if form.is_valid():
                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                bedrooms = form.cleaned_data.get("bedrooms")
                beds = form.cleaned_data.get("beds")
                baths = form.cleaned_data.get("baths")
                instant_book = form.cleaned_data.get("instant_book")
                superhost = form.cleaned_data.get("superhost")
                amenities = form.cleaned_data.get("amenities")
                facilities = form.cleaned_data.get("facilities")

                # Search Filter Queryset
                filter_args = {}

                if city != "Anywhere":
                    filter_args["city__startswith"] = city

                filter_args["country"] = country

                if room_type is not None:
                    filter_args["room_type"] = room_type

                if price is not None:
                    filter_args["price__lte"] = price

                if guests is not None:
                    filter_args["guests__lte"] = guests

                if bedrooms is not None:
                    filter_args["bedrooms__gte"] = bedrooms

                if beds is not None:
                    filter_args["beds__gte"] = beds

                if baths is not None:
                    filter_args["baths__gte"] = baths

                if instant_book is True:
                    filter_args["instant_book"] = True

                if superhost is True:
                    filter_args["host__is_superHost"] = True

                for amenity in amenities:
                    filter_args["amenities"] = amenity

                for facility in facilities:
                    filter_args["facilities"] = facility

                qs = Room.objects.filter(**filter_args).order_by("-created_at")

                paginator = Paginator(qs, 10, orphans=5)

                page = request.GET.get("page", 1)

                rooms = paginator.get_page(page)
                return render(
                    request, "rooms/search.html", {"form": form, "rooms": rooms}
                )

        else:
            form = SearchForm()
            return render(request, "rooms/search.html", {"form": form})

templates/rooms/all_rooms.html
{% extends 'base.html' %}

{% block page_name %}
    Home
{% endblock page_name %}

{% block content %}
{% for room in rooms %}
    <h1>{{ room.name }} - {{ room.price }}</h1>
{% endfor %}
{% endblock content %}

templates/rooms/detail.html
{% extends 'base.html' %}

{% block page_name %}
    Home
{% endblock page_name %}

{% block content %}
    <div>
        <h1>{{ room.name }}</h1>
        <h3>{{ room.description }}</h3>
    </div>
    <div>
        <h2>By: {{ room.host.username }}
            {% if room.host.is_superHost %}
                (superhost)
            {% endif %}
        </h2>
        <h3>Amenities</h3>
        <ul>
        {% for amenity in room.amenities.all %}
            <li>{{ amenity }}</li>
        {% endfor %}
        </ul>
        <h3>Facilities</h3>
        <ul>
        {% for facility in room.facilities.all %}
            <li>{{ facility }}</li>
        {% endfor %}
        </ul>
        <h3>House Rules</h3>
        <ul>
        {% for rule in room.house_rules.all %}
            <li>{{ rule }}</li>
        {% endfor %}
        </ul>
    </div>

{% endblock content %}

templates/rooms/edit_photo.html
{% extends 'base.html' %}

{% block page_title %}
    Update Photo
{% endblock page_title %}

{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto mt-32 mb-10 flex flex-col items-center border p-6 border-gray-400">
        {% include "mixins/room/room_form.html" with form=form cta="Update Photo" %}
    </div>
{% endblock content %}

templates/rooms/photo_create.html
{% extends 'base.html' %}

{% block page_title %}
    Upload Photo
{% endblock page_title %}

{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto mt-32 mb-10 flex flex-col items-center border p-6 border-gray-400">
        {% include "mixins/room/room_form.html" with form=form cta="Upload Photo" %}
    </div>
{% endblock content %}

templates/rooms/photo_edit.html
{% extends 'base.html' %}

{% block page_title %}
    Update Photo
{% endblock page_title %}

{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto mt-32 mb-10 flex flex-col items-center border p-6 border-gray-400">
        {% include "mixins/room/room_form.html" with form=form cta="Update Photo" %}
    </div>
{% endblock content %}

templates/rooms/room_create.html
{% extends 'base.html' %}

{% block page_title %}
    Create Room
{% endblock page_title %}

{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto mt-32 mb-10 flex flex-col items-center border p-6 border-gray-400">
        {% include "mixins/room/room_form.html" with form=form cta="Create Room" %}
    </div>
{% endblock content %}

templates/rooms/room_detail.html
{% extends 'base.html' %}
{% load on_favs %}

{% block page_title %}
    {{ room.name }}
{% endblock page_title %}

{% block content %}

    {# photo grid #}
    <div class="-mt-5 container max-w-full h-75vh mb-20 flex">
        <div class="h-full w-1/2 bg-cove bg-center" style="background-image:url({{ room.first_photo }}"></div>
        <div class="h-full w-1/2 flex flex-wrap">
            {% for photo in room.get_next_four_photos %}
                <div style="background-image:url({{ photo.file.url }})"
                     class="w-1/2 h-auto bg-cover bg-center border-gray-500 border">
                </div>
            {% endfor %}
        </div>
    </div>

    {# room description #}
    <div class="container mx-auto flex justify-around pb-56">
        <div class="w-1/2">
            <div class="flex justify-between">
                <div class="mb-5">
                    <h4 class="text-3xl font-medium mb-px">{{ room.name }}</h4>
                    <span class="text-gray-700 font-light">{{ room.city }}</span>
                </div>
                <a href="{{ room.host.get_absolute_url }}" class="flex flex-col items-center">
                    {% include "mixins/user_avatar.html" with user=room.host %}
                    <span class="mt-2 text-gray-500">{{ room.host.first_name }}</span>
                </a>
            </div>
            <div class="flex border-section">
                <span class="mr-5 font-light">{{ room.room_type }}</span>
                <span class="mr-5 font-light">{{ room.beds }} bed{{ room.beds|pluralize }}</span>
                <span class="mr-5 font-light">{{ room.bedrooms }} bedroom{{ room.bedrooms|pluralize }}</span>
                <span class="mr-5 font-light">{{ room.baths }} bath{{ room.baths|pluralize }}</span>
                <span class="mr-5 font-light">{{ room.guests }} guest{{ room.guests|pluralize }}</span>
            </div>
            <p class="border-section">
                {{ room.description }}
            </p>
            <div class="border-section">
                <h4 class="font-medium text-lg mb-5">Amenities</h4>
                <ul>
                    {% for a in room.amenities.all %}
                        <li class="mb-2">{{ a }}</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="border-section">
                <h4 class="font-medium text-lg mb-5">Facilities</h4>
                <ul>
                    {% for f in room.facilities.all %}
                        <li class="mb-2">{{ f }}</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="border-section">
                <h4 class="font-medium text-lg mb-5">House Rules</h4>
                <ul>
                    {% for h in room.house_rules.all %}
                        <li class="mb-2">{{ h }}</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="mt-10">
                <h4 class="font-medium text-2xl mb-5">Reviews</h4>
                <div class="flex items-center">
                    <div>
                        <i class="fas fa-star text-breeze_bnb"></i>
                        <span class="font-bold text-xl">{{ room.total_rating }}</span>
                    </div>
                    <div class="h-4 w-px bg-gray-400 mx-5"></div>
                    <div>
                        <span class="font-bold text-xl">{{ room.reviews.count }}</span>
                        <span>review{{ room.reviews.count|pluralize }}</span>
                    </div>
                </div>
                <div class="mt-10">
                    {% for review in room.reviews.all %}
                        <div class="border-section">
                            <div class="mb-3 flex">
                                <div>
                                    {% include "mixins/user_avatar.html" with user=review.user h_and_w='w-10 h-10' text='text-xl' %}
                                </div>
                                <div class="flex flex-col ml-5">
                                    <span class="font-medium">{{ review.user.first_name }}</span>
                                    <span class="text-sm text-gray-500">{{ review.created_at|date:"F Y" }}</span>
                                </div>
                            </div>
                            <p>{{ review.review }}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="w-1/3">
            {% if room.host == user %}
                <a href="{% url "rooms:edit" room.pk %}" class="btn-link block">Edit Room</a>
            {% else %}
                {% if not request.session.is_hosting %}
                    {% for calendar in room.get_calendars %}
                        <div class="mb-20">
                            <span class="text-center font-semibold text-lg block mb-8">{{ calendar.get_month }} / {{ calendar.year }}</span>
                            <div class="cal-grid mb-4 font-semibold">
                                {% for day in calendar.day_names %}
                                    <span>{{ day }}</span>
                                {% endfor %}
                            </div>
                            <div class="cal-grid">
                                {% for day in calendar.get_days %}
                                    {% if day.number != 0 %}
                                        {% if day.past %}
                                            <span class="rounded bg-gray-200 w-full text-center p-1 text-gray-300">{{ day }}</span>
                                        {% else %}
                                            <span class="bg-gray-200 w-full text-center rounded text-gray-700 p-1 hover:bg-green-400 hover:font-medium hover:text-white cursor-pointer">{{ day }}</span>
                                        {% endif %}
                                    {% else %}
                                        <span></span>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            {% endif %}
        </div>
    </div>

{% endblock content %}

templates/rooms/room_edit.html
{% extends 'base.html' %}

{% block page_title %}
    Edit Room {{ room.name }}
{% endblock page_title %}

{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto mt-32 mb-10 flex flex-col items-center border p-6 border-gray-400">
        {% include "mixins/room/room_form.html" with form=form cta="Update Room" %}
        <div class="mt-5">
            <a href="{% url "rooms:photos" room.pk %}" class="text-breeze_bnb font-medium">Edit Photos</a>
        </div>
    </div>
{% endblock content %}

templates/rooms/room_list.html
{% extends 'base.html' %}

{% block page_title %}
    Home
{% endblock page_title %}

{% block content %}
    <div class="container mx-auto pb-10">
        <div class="-mx-40 rounded-xl bg-gray-800 h-50vh mt-32 mb-24 bg-center bg-cover"
             style="background-image:url(https://images.unsplash.com/photo-1519046904884-53103b34b206?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80)">
        </div>
        <div class="flex flex-wrap -mx-40 mb-10">
            {% for room in rooms %}
                {% include "mixins/room_card.html" with room=room %}
            {% endfor %}
        </div>
        <div class="flex items-center justify-center mx-auto container">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}" class="text-breeze_bnb">
                    <i class="fas fa-angle-double-left fa-lg"></i>
                </a>
            {% endif %}

            <span class="mx-2 font-medium text-lg">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" class="text-breeze_bnb">
                    <i class="fas fa-angle-double-right fa-lg"></i>
                </a>
            {% endif %}
        </div>
    </div>
{% endblock content %}

templates/rooms/room_photos.html
{% extends 'base.html' %}

{% block page_title %}
    {{ room.name }} photos
{% endblock page_title %}

{% block content %}
    <div class="container mx-auto mt-32 mb-10 flex flex-col">
        <div class="my-10 w-full">
            <a href="{% url "rooms:add-photos" room.pk %}" class="btn-link w-1/6 block">Upload Photo</a>
        </div>
        {% for photo in room.photos.all %}
            <div class="mb-5 border p-6 border-gray-400 flex justify-between">
                <div class="flex items-start">
                    <img src="{{ photo.file.url }}" class="w-32 h032"/>
                    <span class="ml-5 text-xl">{{ photo.caption }}</span>
                </div>
                <div class="flex flex-col w-1/5">
                    <a class="btn-link mb-5 bg-green-500" href="{% url "rooms:edit-photo" room.pk photo.pk %}">Edit</a>
                    <a class="btn-link bg-red-600" href="{% url "rooms:delete-photo" room.pk photo.pk %}">Delete</a>
                </div>
            </div>
        {% endfor %}
        <div class="flex justify-center">
            <a href="{% url "rooms:edit" room.pk %}" class="text-breeze_bnb font-medium font-2xl mt-5">Back to Edit
                Room</a>
        </div>
    </div>
{% endblock content %}

templates/rooms/search.html
{% extends "base.html" %}

{% block page_title %}
    Search
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <h1> Search </h1>

    <form method="GET" action="{% url "rooms:search" %}">
        {{ form.as_p }}
        <button>search </button>
    </form>

    <h3>Results</h3>
    {% for room in rooms %}
        <h3>{{ room.name }}</h3>
    {% endfor %}


{% endblock %}