config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("", include('core.urls', namespace="core")),
    path('rooms/', include('rooms.urls', namespace='rooms')),
    path('users/', include('users.urls', namespace='users')),
    path('lists/', include('lists.urls', namespace='lists')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
from rooms import views as rooms_views

app_name = "core"

urlpatterns = [
    path("", rooms_views.HomeView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path

from rooms.views import RoomDetail, EditRoomView, CreateRoomView, SearchView, RoomPhotosView, delete_photo, EditPhotoView, AddPhotoView

app_name = "rooms"

urlpatterns = [
    path("create/", CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", AddPhotoView.as_view(), name="add-photos"),
    path("<int:room_pk>/photos/<int:photo_pk>/delete/", delete_photo, name="delete-photo"),
    path("<int:room_pk>/photos/<int:photo_pk>/edit/", EditPhotoView.as_view(), name="edit-photo"),
    path("search/", SearchView.as_view(), name="search"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="x-ua-compatible" content="ie=edge"/>
    <link rel="icon" href="/static/img/favicon.ico">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css"/>
    <link rel="stylesheet" href="{% static "css/styles.css" %}"/>
    <title> {% block page_title %}{% endblock page_title %}| Breeze_bnb</title>
</head>
<body class="text-gray-800 mt-24 font-light">
{% include "partials/messages.html" %}
<header class="container max-w-full inset-0 flex items-center justify-between px-6 h-24 border-b border-gray-400 fixed bg-white">
    <div class="flex items-center w-1/3">
        <a href="{% url "core:home" %}" class="mr-6">
            <img class="w-8" src="{% static "img/logo.png" %}" alt="Breeze_bnb"/>
        </a>
        {% block search-bar %}
            <form method="GET" action="{% url 'rooms:search' %}" class="w-9/12">
                <input class="search-box border px-5 w-full font-medium text-gray-900 placeholder-gray-600 py-3 rounded-sm w-64 shadow-md hover:shadow-lg focus-within:outline-none"
                       id="city" name="city" placeholder="Search by City"/>
            </form>
        {% endblock search-bar %}
    </div>
    <div>
        {% include 'partials/nav.html' %}
    </div>
</header>
{% block content %}
{% endblock content %}
{% include 'partials/footer.html' %}
</body>
</html>