config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("", include('core.urls', namespace="core")),
    path('rooms/', include('rooms.urls', namespace='rooms')),
    path('users/', include('users.urls', namespace='users')),
    path('lists/', include('lists.urls', namespace='lists')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
from rooms import views as rooms_views

app_name = "core"

urlpatterns = [
    path("", rooms_views.HomeView.as_view(), name="home"),
]

users/urls.py
from django.urls import path

from users.views import LoginView, log_out, SignUpView, complete_verification, github_login, github_callback, \
    kakao_callback, kakao_login, UserProfileView, UpdateUserProfileView, UpdateUserPasswordView, switch_hosting

app_name = "users"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("login/github/", github_login, name="github-login"),
    path("login/github/callback/", github_callback, name="github-callback"),
    path("login/kakao/", kakao_login, name="kakao-login"),
    path("login/kakao/callback/", kakao_callback, name="kakao-callback"),
    path("logout/", log_out, name="logout"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("verify/<str:key>/", complete_verification, name="complete_verification"),
    path("<int:pk>/", UserProfileView.as_view(), name="profile"),
    path("update-profile/", UpdateUserProfileView.as_view(), name="update"),
    path("update-password/", UpdateUserPasswordView.as_view(), name="update-password"),
    path("switch-hosting/", switch_hosting, name="switch-hosting"),
]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from users.models import User


class LoginForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "Email"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Password"}))

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        try:
            user = User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("Password is wrong."))
                # cf) non_field_error
                # self.add_error(None, forms...)
        except User.DoesNotExist:
            self.add_error("email", forms.ValidationError("User does not exist."))


"""
# Refactoring by UserCreationForm
class SignUpForm(UserCreationForm):
    username = forms.EmailField(label="email")

    class Meta:
        model = User
        fields = ("username",)
"""


class SignUpForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("first_name", "last_name", "email",)
        widgets = {
            "first_name": forms.TextInput(attrs={"placeholder": "First Name"}),
            "last_name": forms.TextInput(attrs={"placeholder": "Last Name"}),
            "email": forms.EmailInput(attrs={"placeholder": "Email"}),
        }

    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Password"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Confirm Password"}))

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            User.objects.get(email=email)
            raise forms.ValidationError("User already exists with this email.")
        except User.DoesNotExist:
            return email

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")

        if password != password1:
            raise forms.ValidationError("Password confirmation does note match.")
        else:
            return password

    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user.username = email
        user.set_password(password)
        user.save()

    """
    # refactoring by ModelForms
    first_name = forms.CharField(max_length=80)
    last_name = forms.CharField(max_length=80)
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    password1 = forms.CharField(widget=forms.PasswordInput, label="Confirm Password")

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            User.objects.get(email=email)
            raise forms.ValidationError("User already exists with this email.")
        except User.DoesNotExist:
            return email

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")

        if password != password1:
            raise forms.ValidationError("Password confirmation does note match.")
        else:
            return password

    def save(self):
        first_name = self.cleaned_data.get("first_name")
        last_name = self.cleaned_data.get("last_name")
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        user = User.objects.create_user(email, email, password)
        user.first_name = first_name
        user.last_name = last_name
    """

users/views.py
import requests
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.files.base import ContentFile
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import FormView, DetailView, UpdateView

from mixins import LoggedOutOnlyView, LoggedInOnlyView, EmailLoginOnlyView
from settings import config
from users.models import User
from users.forms import LoginForm, SignUpForm


class LoginView(LoggedOutOnlyView, FormView):
    template_name = "users/login.html"
    form_class = LoginForm

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
            return redirect(reverse("core:home"))
        return super().form_valid(form)

    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            return reverse("core:home")

    """  Refactoring Using FormView 
    def get(self, request):
        form = LoginForm(initial={"email": "abc@de.com"})
        return render(request, "users/login.html", {"form": form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=email, password=password)

            if user is not None:
                login(request, user)
                return redirect(reverse("core:home"))
        return render(request, "users/login.html", {"form": form})
    """


def log_out(request):
    messages.info(request, "See you later")
    logout(request)
    return redirect(reverse("core:home"))


class SignUpView(FormView):
    template_name = "users/signup.html"
    form_class = SignUpForm
    success_url = reverse_lazy("core:home")

    # count = User.objects.last().pk
    # initial = {
    #     "first_name": "user",
    #     "last_name": f"test{count}",
    #     "email": f"berzzubunny+test{count}@gmail.com",
    # }

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        user.verify_email()
        return super().form_valid(form)


def complete_verification(request, key):
    try:
        user = User.objects.get(email_secret=key)
        user.email_verified = True
        user.email_secret = ""
        user.save()
        # TODO : add success msg
    except User.DoesNotExist:
        # TODO : add error msg
        pass
    return redirect(reverse("core:home"))


def github_login(request):
    client_id = config["GH_ID"]
    redirect_uri = "http://127.0.0.1:8000/users/login/github/callback"
    return redirect(
        f"https://github.com/login/oauth/authorize?client_id={client_id}&redirect_url={redirect_uri}&scope=user:email&allow_signup=false"
    )


class GithubException(Exception):
    pass


def github_callback(request):
    try:
        client_id = config["GH_ID"]
        client_secret = config["GH_SECRET"]
        code = request.GET.get("code", None)
        if code is not None:
            result = requests.post(
                f"https://github.com/login/oauth/access_token?client_id={client_id}&client_secret={client_secret}&code={code}",
                headers={"Accept": "application/json"},
            )
            result_json = result.json()
            error = result_json.get("error", None)
            if error is not None:
                return GithubException("Can't get access token")
            else:
                access_token = result_json.get("access_token")
                profile_request = requests.get(
                    "https://api.github.com/user",
                    headers={
                        "Authorization": f"token {access_token}",
                        "Accept": "application/json",
                    },
                )
                email_request = requests.get(
                    "https://api.github.com/user/emails",
                    headers={
                        "Authorization": f"token {access_token}",
                        "Accept": "application/json",
                    },
                )
                profile_json = profile_request.json()
                email_json = email_request.json()
                username = profile_json.get("login", None)
                if username is not None:
                    name = profile_json.get("name")
                    email = email_json[0].get("email")
                    bio = profile_json.get("bio")

                    # blank 검증
                    name = "" if name is None else name
                    bio = "" if bio is None else bio

                    try:
                        user = User.objects.get(email=email)
                        if user.login_method != User.LOGIN_GITHUB:
                            # 다른 방식으로 같은 메일을 사용하여 소셜 로그인을 한 경우
                            raise GithubException(
                                f"Please log in with: {user.login_mehtod}"
                            )
                    except User.DoesNotExist:
                        # 신규 소셜 로그인 가입
                        user = User.objects.create(
                            email=email,
                            first_name=name,
                            username=email,
                            bio=bio,
                            login_method=User.LOGIN_GITHUB,
                            email_verified=True,
                        )
                        user.set_unusable_password()  # 소셜 로그인 계정에 발급하는 임시 비밀번호
                        user.save()
                    login(request, user)
                    messages.success(request, f"Welcome back {user.first_name}")
                    return redirect(reverse("core:home"))
                else:
                    raise GithubException("Can't get your profile")
        else:
            raise GithubException("Can't get code")
    except GithubException as e:
        messages.error(request, e)
        return redirect(reverse("users:login"))


def kakao_login(request):
    client_id = config["K_KEY"]
    redirect_uri = "http://127.0.0.1:8000/users/login/kakao/callback"
    return redirect(
        f"https://kauth.kakao.com/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&response_type=code"
    )


class KakaoException(Exception):
    pass


def kakao_callback(request):
    try:
        code = request.GET.get("code")
        client_id = config["K_KEY"]
        redirect_uri = "http://127.0.0.1:8000/users/login/kakao/callback"
        token_request = requests.get(
            f"https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={client_id}&redirect_uri={redirect_uri}&code={code}"
        )
        token_json = token_request.json()
        print(token_json)
        error = token_json.get("error", None)
        if error is not None:
            raise KakaoException("not Token")
        access_token = token_json.get("access_token")
        profile_request = requests.get(
            "https://kapi.kakao.com/v2/user/me",
            headers={
                "Authorization": f"Bearer {access_token}",
            },
        )
        profile_json = profile_request.json()

        # 이메일 추출
        email = profile_json.get("kakao_account").get("email", None)

        # 이메일 동의 안하면 나가리
        if email is None:
            raise KakaoException(
                "Can't get authorization code. Please confirm your Email agreement."
            )

        # 닉네임, 프로필 추출
        properties = profile_json.get("properties")
        nickname = properties.get("nickname")
        profile_image = properties.get("profile_image")

        try:
            # 이전에 카카오 계정으로 로그인 했는지 검증
            user = User.objects.get(email=email)
            if user.login_method != User.LOGIN_KAKAO:
                raise KakaoException("Please also give me your email")
        except User.DoesNotExist:
            # 없으니까 계정 만듬
            user = User.objects.create(
                email=email,
                username=email,
                first_name=nickname,
                login_method=User.LOGIN_KAKAO,
                email_verified=True,
            )
            user.set_unusable_password()
            user.save()
            if profile_image is not None:
                photo_request = requests.get(profile_image)
                user.avatar.save(
                    f"{nickname}-avatar", ContentFile(photo_request.content)
                )
        messages.success(request, f"Welcome back {user.first_name}")
        login(request, user)
        return redirect(reverse("core:home"))

    except KakaoException as e:
        messages.error(request, e)
        return redirect(reverse("users:login"))


class UserProfileView(DetailView):
    model = User
    # 현재 로그인한 유저 호출
    context_object_name = "user_obj"


class UpdateUserProfileView(LoggedInOnlyView, SuccessMessageMixin, UpdateView):
    model = User
    template_name = "users/update-profile.html"
    context_object_name = "user_obj"
    success_message = "Update Profile Success!"
    fields = (
        "first_name",
        "last_name",
        "bio",
        "gender",
        "birthday",
        "language",
        "currency",
    )

    def get_object(self, queryset=None):
        return self.request.user

templates/users/login.html
{% extends "base.html" %}

{% block page_title %}
    Login
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto mt-32 mb-10 flex flex-col items-center border p-6 border-gray-400">

        {% include "partials/social_login.html" %}

        {% include "mixins/auth/auth_form.html" with form=form cta="Log in" %}

        <div class="mt-3">
            <span class="mr-2">Don't have an account?</span>
            <a href="{% url "users:signup" %}" class="text-breeze_bnb font-medium">Sign Up</a>
        </div>
    </div>
{% endblock %}

templates/users/signup.html
{% extends "base.html" %}

{% block page_title %}
    Sign Up
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto mt-32 mb-10 flex flex-col items-center border p-6 border-gray-400">

        {% include "partials/social_login.html" %}

        {% include "mixins/auth/auth_form.html" with form=form cta="Sign up" %}

        <div class="mt-3">
            <span class="mr-2">Have an account?</span>
            <a href="{% url "users:login" %}" class="text-breeze_bnb font-medium">Log in</a>
        </div>
    </div>
{% endblock %}

templates/users/update-password.html
{% extends "base.html" %}

{% block page_title %}
    Change Your Password
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <div class="min-h-75vh">
        <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">
            {% include "mixins/auth/auth_form.html" with form=form cta="Update Password" %}
        </div>
    </div>
{% endblock %}

templates/users/update-profile.html
{% extends "base.html" %}

{% block page_title %}
    Update Your Profile
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto mt-32 mb-10 flex flex-col items-center border p-6 border-gray-400">
        {% include "mixins/auth/auth_form.html" with form=form cta="Update Profile" %}
        {% if user_obj.login_method == "email" %}
            <div class="mt-5"><a href="{% url "users:update-password" %}" class="text-breeze_bnb font-medium" >Change Password</a></div>
        {% endif %}
    </div>
{% endblock %}

templates/users/user_detail.html
{% extends "base.html" %}

{% block page_title %}
    {{ user_obj.first_name }}'s Profile
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <div class="min-h-75vh">
        <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto mt-32 mb-10 flex flex-col items-center border p-6 border-gray-400">

            {% include "mixins/user_avatar.html" with user=user_obj %}

            <div class="flex items-center">
                <span class="text-2xl mt-3">{{ user_obj.first_name }}</span>
                {% if user_obj.is_superHost %}
                    <i class="fa fa-check-circle text-breeze_bnb ml-1"></i>
                {% endif %}
            </div>
            <span class="text-lg mt-2 mb-5">{{ user_obj.bio }}</span>

            {% if user == user_obj %}
                <a href="{% url "users:update" %}" class="btn-link">Edit Profile</a>
            {% endif %}
        </div>
        {% if user_obj.rooms.all.count > 0 %}
            <h3 class="mb-12 text-2xl text-center">{{ user_obj.first_name }}'s rooms</h3>
            <div class="container mx-auto pb-10">
                <div class="flex flex-wrap mb-10 w-full">
                    {% for room in user_obj.rooms.all %}
                        {% include "mixins/room_card.html" with room=room %}
                    {% endfor %}
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}